version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=book-db
      - POSTGRES_USER=book-admin
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
